engines:
  coffeelint:
    enabled: true
  csslint:
    enabled: true
ratings:
   paths:
   - app/coffeescript/**
   - app/css/**
exclude_paths:
- app/bower_components/**
- app/js/**
- dist/**/*
- test/**/*
- node_modules/**/*
