rules:
  indent:
    - 0
  quotes:
    - 0
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  no-unused-vars:
    - 1
  no-undef:
    - 1
env:
  browser: true
extends: 'eslint:recommended'
